[workspace]
resolver = "2"

[package]
name = "deputy-extension"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT"

[lib]
path = "src/extension.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.4"
