id = "deputy"
name = "Deputy"
version = "0.1.0"
schema_version = 1
authors = ["Filip Tibell <filip.tibell@gmail.com>", "teapo <4teapo@gmail.com>"]
description = "A language server for your dependencies."
repository = "https://github.com/filiptibell/deputy"

[language_servers.deputy]
name = "Deputy"
languages = ["TOML", "JSON"]

[slash_commands.deputy-set-github-pat]
description = "Sets the GitHub personal access token Deputy should use."
requires_argument = true

[slash_commands.deputy-remove-github-pat]
description = "Removes the GitHub personal access token Deputy should use."
requires_argument = false
